version: '3.9'

services:
  service_notification:
    image: 121113815220.dkr.ecr.us-west-2.amazonaws.com/charging-prod-us-west-2-ecr-consumer:notification-latest
    build:
      context: ./
      dockerfile: ./apps/notification/Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3002:3002
    volumes:
      - .:/apps/notification
  
  service_logger:
    image: 121113815220.dkr.ecr.us-west-2.amazonaws.com/charging-prod-us-west-2-ecr-consumer:logger-latest
    build:
      context: ./
      dockerfile: ./apps/logger/Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3000:3000
    volumes:
      - .:/apps/logger
  
  service_api_auth:
    image: 121113815220.dkr.ecr.us-west-2.amazonaws.com/charging-prod-us-west-2-ecr-consumer:api-auth-latest
    build:
      context: ./
      dockerfile: ./apps/api-auth/Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3001:3001
    volumes:
      - .:/apps/api-auth
  
  service_gateway:
    image: 121113815220.dkr.ecr.us-west-2.amazonaws.com/charging-prod-us-west-2-ecr-consumer:gateway-latest
    build:
      context: ./
      dockerfile: ./apps/gateway/Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3006:80
    volumes:
      - .:/apps/gateway
  
  service_payment:
    image: 121113815220.dkr.ecr.us-west-2.amazonaws.com/charging-prod-us-west-2-ecr-consumer:payment-latest
    build:
      context: ./
      dockerfile: ./apps/payment/Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3005:3005
    volumes:
      - .:/apps/payment